### ISSUE TITLE
mniVertstatsFile::loadOldStyleFile contains infinite loop

### ISSUE THREAD

**Issue by sghanavati** [BIC-MNI/oobicpl#1]
Hi,
The most recent update to the mniVertstatsFile::loadOldStyleFile fuction causes an infinite loop in :
while( nextpos = line.find_first_of(" \t\n",firstpos) != string::npos ) {
     firstpos = nextpos+1;
     this->numColumns++;
   }

I have tested the following which is seems to work poperly:

// Added by Sahar to skip the spaces and tabs at the beginning of the line. July 11, 2014
  firstpos = line.find_first_not_of(" \t\n",0);

  while (nextpos != string::npos) {
    nextpos = line.find_first_of(" \t\n",firstpos);
    firstpos = nextpos+1;
    this->numColumns++;
  }

Thanks

**Comment by gdevenyi** [comment]
Fixed. Can't seem to close issues in some repos, permission issue?

**Comment by vfonov** [comment]
i changed permission

**Comment by gdevenyi** [comment]
Fixed. Cheers.
